# On every push this script is executed
on: push
name: Build Zola and deploy GH Pages
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v4
      - name: build
        uses: shalzz/zola-deploy-action@v0.18.0
        env:
          BUILD_DIR: resume_v2
          BUILD_ONLY: true
      - uses: browser-actions/setup-chrome@v1
        id: setup-chrome
      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libasound2t64 \
            libatk-bridge2.0-0t64 \
            libatk1.0-0t64 \
            libcairo2 \
            libcups2t64 \
            libdbus-1-3 \
            libexpat1 \
            libgbm1 \
            libglib2.0-0t64 \
            libnss3 \
            libpango-1.0-0 \
            libxcomposite1 \
            libxdamage1 \
            libxfixes3 \
            libxkbcommon0 \
            libxrandr2
      - name: generate-pdfs
        run: |
          ${{ steps.setup-chrome.outputs.chrome-path }} --headless --disable-gpu --no-margins --no-pdf-header-footer --print-to-pdf=resume_v2/static/david-pollack-resume.pdf resume_v2/public/index.html
          ${{ steps.setup-chrome.outputs.chrome-path }} --headless --disable-gpu --no-margins --no-pdf-header-footer --print-to-pdf=resume_v2/static/david-pollack-cover-letter.pdf resume_v2/public/coverletter-with-frontmatter/index.html
      # Build & deploy
      - name: deploy
        uses: shalzz/zola-deploy-action@v0.18.0
        env:
          # Zola Repo dir
          BUILD_DIR: resume_v2
          # Target branch
          PAGES_BRANCH: gh-pages
          # Provide personal access token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
